---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: papliba-corp
  description: The Papliba Corp, a gaming organization
  links:
    - url: http://www.papliba.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Papliba Corp
    email: papliba@outlook.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Maggie&flip=true&backgroundColor=ffdfbf
  children: [c-suite, administrative-support, operations-production, technology-development, sales-customer-relations, marketing-communication, strategic-business-development, specialized-teams]
---
